import {
  activateAdmission,
  editAdmissionFunction,
  fetchAdmission,
  fetchOngoing,
  fetchCompleted,
  fetchRemainingArray,
  fetchAdmissionRemainingArray,
  atInstituteSearchApplication,
  userApply,
  newApplication,
  fetchRequest,
  fetchSelect,
  fetchConfirm,
  fetchConfirmAll,
  userSelect,
  userCancelApplication,
  userSelectStatusMode,
  userConfirm,
  userCancel,
  fetchClasses,
  newClassAllot,
  markComplete,
  oneStudentFee,
  paidRemainFee,
  oneApplication,
  allDepartment,
  cancelStatusMode,
  studentAdmission,
  collectApplicantDocsFunction,
  admissionBatchListFunction,
  admissionAllottedListFunction,
  admissionCancelledListFunction,
  admissionClassMasterListFunction,
  addEnquiryFunction,
  getAllEnquiryListFunction,
  getOneEnquiryFunction,
  oneEnquiryActionFunction,
  directJoinFormAdmissionFunction,
  submitAmountToFinanaceFunction,
  getAccountWithNumberFunction,
  editFeeStructureFunction,
  confirmStudentModeByAdmissionAdminFunction,
  rejectStudentModeByAdmissionAdminFunction,
  getReceiptByAdmissionFunction,
  receiptActionByAdmissionFunction,
  reApplyReceiptByStudentFunction,
  getFeeReceiptDetailFunction,
  getDocumentByAdmissionFuction,
  addDocumentByAdmissionFuction,
  updateDocumentByAdmissionFuction,
  deleteDocumentByAdmissionFuction,
  refundAmountByAdmissionAdminFunction,
  getRefundByAdmissionFuction,
  updateRemarkByAdmissionAdminFunction,
  exportFilterDataByAdmissionFuction,
  getAllExcelByAdmissionAdminFunction,
  payAdmissionFeeByStudentFunction,
  updateExcelByAdmissionAdminFunction,
  deleteExcelByAdmissionAdminFunction,
  updateDocumentByAdmissionAdminFunction,
  deleteDocumentByAdmissionAdminFunction,
  addModeratorByAdmissionAdminFunction,
  getModeratorByAdmissionAdminFunction,
  updateModeratorByAdmissionAdminFunction,
  deleteModeratorByAdmissionAdminFunction,
  admissionGetSiteInfoFunction,
  admissionUpdateSiteInfoFunction,
  getScholarshipListAdmissionFunction,
  addScholarshipAdmissionFunction,
  getOneScholarshipAdmissionFunction,
  getOneScholarshipAllCandidateAdmissionFunction,
  oneSchloarshipActionAdmissionFunction,
  addScholarshipFundCorpusAdmissionFunction,
  getScholarshipFundCorpusAdmissionFunction,
  addMoreScholarshipFundCorpusAdmissionFunction,
  updateApplicationByAdmissionFunction,
  deleteApplicationByAdmissionFunction,
  forgetPasswordProtectionFunction,
  passwordProtectionToggleFunction,
  passwordProtectionLoginFunction,
  updateFeeStructureByAppliationWiseFunction,
  getRefundedListByAdmissionFunction,
  directJoinFormWithPayAdmissionFunction,
  collectSetOffAdmissionFeesFunction,
  admissionDocsActionByStudentFunction,
  scholarShipExcelByAdmissionFunction,
  scholarShipExcelByInstituteFunction,
  addScholarNumberAdmissionFunction,
  studentDepartmentFeesFunction,
  studentBacklogFeesFunction,
  internalFeeReceiptFunction,
  dropAdmissionFeesCardByAdmissionFunction,
  allApplicationByAdmissionFunction,
  addNewFeesByAdmissionFunction,
  collectNewAddFeesByAdmissionFunction,
  governmentCollectNewAddFeesByAdmissionFunction,
  admissionReminderFunction,
  admissionInstallmentEditFeesByAdmissionFunction,
  getPendingCustomFilterByAdmissionFunction,
  getBatchStandardWithMultipleDepartmentFunction,
  getDailyCollectionByAdmissionFunction,
  editStudentGrNumberFunction,
  //
  admissionRevertBackSelectedToApplicationFunction,
  admissionRevertBackDocsToSelectedFunction,
  removeFeesInstallmentCardFunction,
  transferApplicatToOtherApplicationFunction,
  existStudentFeesExcelByAdmissionFunction,
  studentValidaForApplicationByAdmissionFunction,
  studentBankValidationByAdmissionFunction,
  markCompleteToOngoingApplicationFunction,
  getReminderHistoryByAdmissionFunction,
  getOsReminderStudentListFunction,
  studentScholarshipNumberDublicateFunction,
} from "./admissionBuilderAPI";
import { admissionNewApi } from "./admissionNewApi";

//////////eeghfrwjeghw
export const admissionApiDynamic = admissionNewApi.injectEndpoints({
  endpoints: (builder) => ({
    activateAdmissionHead: activateAdmission(builder),
    editAdmission: editAdmissionFunction(builder),
    fetchAdmissionDetail: fetchAdmission(builder),
    fetchAllOngoingApp: fetchOngoing(builder),
    fetchAllCompletedApp: fetchCompleted(builder),
    fetchAllRemainingArray: fetchRemainingArray(builder),
    fetchAdmissionRemainingArray: fetchAdmissionRemainingArray(builder),

    fetchAllAppAtInstitute: atInstituteSearchApplication(builder),
    newUserApply: userApply(builder),
    getNewApplication: newApplication(builder),
    getAllRequest: fetchRequest(builder),
    getAllSelect: fetchSelect(builder),
    getAllConfirm: fetchConfirm(builder),
    getAllConfirmMultiselect: fetchConfirmAll(builder),
    fetchUserSelectApp: userSelect(builder),
    fetchUserCancelApp: userCancelApplication(builder),
    fetchUserSelectStatusApp: userSelectStatusMode(builder),
    getUserConfirm: userConfirm(builder),
    getUserCancel: userCancel(builder),
    getAllClasses: fetchClasses(builder),
    retrieveNewClassAllot: newClassAllot(builder),
    retrieveMarkComplete: markComplete(builder),
    getOneViewStudentFee: oneStudentFee(builder),
    retrievePaidRemainFee: paidRemainFee(builder),
    getOneApplication: oneApplication(builder),
    getAllDepartment: allDepartment(builder),
    fetchCancelStatusMode: cancelStatusMode(builder),
    renderStudentAdmissionFees: studentAdmission(builder),
    collectApplicantDocs: collectApplicantDocsFunction(builder),
    admissionBatchList: admissionBatchListFunction(builder),
    admissionAllottedList: admissionAllottedListFunction(builder),
    admissionCancelledList: admissionCancelledListFunction(builder),
    admissionClassMasterList: admissionClassMasterListFunction(builder),
    addEnquiry: addEnquiryFunction(builder),
    getAllEnquiryList: getAllEnquiryListFunction(builder),
    getOneEnquiry: getOneEnquiryFunction(builder),
    oneEnquiryAction: oneEnquiryActionFunction(builder),
    directJoinFormAdmission: directJoinFormAdmissionFunction(builder),
    submitAmountToFinanace: submitAmountToFinanaceFunction(builder),
    getAccountWithNumber: getAccountWithNumberFunction(builder),
    editFeeStructure: editFeeStructureFunction(builder),
    confirmStudentModeByAdmissionAdmin:
      confirmStudentModeByAdmissionAdminFunction(builder),
    rejectStudentModeByAdmissionAdmin:
      rejectStudentModeByAdmissionAdminFunction(builder),

    getReceiptByAdmission: getReceiptByAdmissionFunction(builder),
    receiptActionByAdmission: receiptActionByAdmissionFunction(builder),
    reApplyReceiptByStudent: reApplyReceiptByStudentFunction(builder),
    getFeeReceiptDetail: getFeeReceiptDetailFunction(builder),
    getDocumentByAdmission: getDocumentByAdmissionFuction(builder),
    addDocumentByAdmission: addDocumentByAdmissionFuction(builder),
    updateDocumentByAdmission: updateDocumentByAdmissionFuction(builder),
    deleteDocumentByAdmission: deleteDocumentByAdmissionFuction(builder),
    refundAmountByAdmissionAdmin: refundAmountByAdmissionAdminFunction(builder),
    getRefundByAdmission: getRefundByAdmissionFuction(builder),
    updateRemarkByAdmissionAdmin: updateRemarkByAdmissionAdminFunction(builder),
    exportFilterDataByAdmission: exportFilterDataByAdmissionFuction(builder),
    getAllExcelByAdmissionAdmin: getAllExcelByAdmissionAdminFunction(builder),
    payAdmissionFeeByStudent: payAdmissionFeeByStudentFunction(builder),
    updateExcelByAdmissionAdmin: updateExcelByAdmissionAdminFunction(builder),
    deleteExcelByAdmissionAdmin: deleteExcelByAdmissionAdminFunction(builder),
    updateDocumentByAdmissionAdmin:
      updateDocumentByAdmissionAdminFunction(builder),
    deleteDocumentByAdmissionAdmin:
      deleteDocumentByAdmissionAdminFunction(builder),
    addModeratorByAdmissionAdmin: addModeratorByAdmissionAdminFunction(builder),
    getModeratorByAdmissionAdmin: getModeratorByAdmissionAdminFunction(builder),
    updateModeratorByAdmissionAdmin:
      updateModeratorByAdmissionAdminFunction(builder),
    deleteModeratorByAdmissionAdmin:
      deleteModeratorByAdmissionAdminFunction(builder),
    admissionGetSiteInfo: admissionGetSiteInfoFunction(builder),
    admissionUpdateSiteInfo: admissionUpdateSiteInfoFunction(builder),
    getScholarshipListAdmission: getScholarshipListAdmissionFunction(builder),
    addScholarshipAdmission: addScholarshipAdmissionFunction(builder),
    getOneScholarshipAdmission: getOneScholarshipAdmissionFunction(builder),
    getOneScholarshipAllCandidateAdmission:
      getOneScholarshipAllCandidateAdmissionFunction(builder),
    oneSchloarshipActionAdmission:
      oneSchloarshipActionAdmissionFunction(builder),
    addScholarshipFundCorpusAdmission:
      addScholarshipFundCorpusAdmissionFunction(builder),
    getScholarshipFundCorpusAdmission:
      getScholarshipFundCorpusAdmissionFunction(builder),
    addMoreScholarshipFundCorpusAdmission:
      addMoreScholarshipFundCorpusAdmissionFunction(builder),
    updateApplicationByAdmission: updateApplicationByAdmissionFunction(builder),
    deleteApplicationByAdmission: deleteApplicationByAdmissionFunction(builder),
    forgetPasswordProtection: forgetPasswordProtectionFunction(builder),
    passwordProtectionToggle: passwordProtectionToggleFunction(builder),
    passwordProtectionLogin: passwordProtectionLoginFunction(builder),
    updateFeeStructureByAppliationWise:
      updateFeeStructureByAppliationWiseFunction(builder),

    getRefundedListByAdmission: getRefundedListByAdmissionFunction(builder),
    directJoinFormWithPayAdmission:
      directJoinFormWithPayAdmissionFunction(builder),
    collectSetOffAdmissionFees: collectSetOffAdmissionFeesFunction(builder),
    admissionDocsActionByStudent: admissionDocsActionByStudentFunction(builder),
    scholarShipExcelByAdmission: scholarShipExcelByAdmissionFunction(builder),
    scholarShipExcelByInstitute: scholarShipExcelByInstituteFunction(builder),
    addScholarNumberAdmission: addScholarNumberAdmissionFunction(builder),
    studentDepartmentFees: studentDepartmentFeesFunction(builder),
    studentBacklogFees: studentBacklogFeesFunction(builder),
    internalFeeReceipt: internalFeeReceiptFunction(builder),
    dropAdmissionFeesCardByAdmission:
      dropAdmissionFeesCardByAdmissionFunction(builder),

    allApplicationByAdmission: allApplicationByAdmissionFunction(builder),
    addNewFeesByAdmission: addNewFeesByAdmissionFunction(builder),
    collectNewAddFeesByAdmission: collectNewAddFeesByAdmissionFunction(builder),
    governmentCollectNewAddFeesByAdmission:
      governmentCollectNewAddFeesByAdmissionFunction(builder),
    admissionReminder: admissionReminderFunction(builder),
    admissionInstallmentEditFeesByAdmission:
      admissionInstallmentEditFeesByAdmissionFunction(builder),
    getPendingCustomFilterByAdmission:
      getPendingCustomFilterByAdmissionFunction(builder),
    getBatchStandardWithMultipleDepartment:
      getBatchStandardWithMultipleDepartmentFunction(builder),
    getDailyCollectionByAdmission:
      getDailyCollectionByAdmissionFunction(builder),
    editStudentGrNumber: editStudentGrNumberFunction(builder),
    admissionRevertBackSelectedToApplication:
      admissionRevertBackSelectedToApplicationFunction(builder),
    admissionRevertBackDocsToSelected:
      admissionRevertBackDocsToSelectedFunction(builder),
    removeFeesInstallmentCard: removeFeesInstallmentCardFunction(builder),
    transferApplicatToOtherApplication:
      transferApplicatToOtherApplicationFunction(builder),
    existStudentFeesExcelByAdmission:
      existStudentFeesExcelByAdmissionFunction(builder),
    studentValidaForApplicationByAdmission:
      studentValidaForApplicationByAdmissionFunction(builder),
    studentBankValidationByAdmission:
      studentBankValidationByAdmissionFunction(builder),
    markCompleteToOngoingApplication:
      markCompleteToOngoingApplicationFunction(builder),
    getReminderHistoryByAdmission:
      getReminderHistoryByAdmissionFunction(builder),
    getOsReminderStudentList: getOsReminderStudentListFunction(builder),
    studentScholarshipNumberDublicate:
      studentScholarshipNumberDublicateFunction(builder),
  }),
});

export const {
  useActivateAdmissionHeadMutation,
  useEditAdmissionMutation,
  useFetchAdmissionDetailQuery,
  useFetchAllOngoingAppQuery,
  useFetchAllCompletedAppQuery,
  useFetchAllRemainingArrayQuery,
  useFetchAdmissionRemainingArrayMutation,
  useFetchAllAppAtInstituteQuery,
  useNewUserApplyMutation,
  useGetNewApplicationMutation,
  useGetAllRequestQuery,
  useGetAllSelectQuery,
  useGetAllConfirmQuery,
  useGetAllConfirmMultiselectQuery,
  useFetchUserSelectAppMutation,
  useFetchUserCancelAppMutation,
  useFetchUserSelectStatusAppMutation,
  useGetUserConfirmMutation,
  useGetUserCancelMutation,
  useGetAllClassesQuery,
  useRetrieveNewClassAllotMutation,
  useRetrieveMarkCompleteMutation,
  useGetOneViewStudentFeeQuery,
  useRetrievePaidRemainFeeMutation,
  useGetOneApplicationQuery,
  useGetAllDepartmentQuery,
  useFetchCancelStatusModeMutation,
  useRenderStudentAdmissionFeesQuery,
  useCollectApplicantDocsMutation,
  useAdmissionBatchListQuery,
  useAdmissionAllottedListQuery,
  useAdmissionCancelledListQuery,
  useAdmissionClassMasterListQuery,
  useAddEnquiryMutation,
  useGetAllEnquiryListQuery,
  useGetOneEnquiryQuery,
  useOneEnquiryActionMutation,
  useDirectJoinFormAdmissionMutation,
  useSubmitAmountToFinanaceMutation,
  useGetAccountWithNumberQuery,
  useEditFeeStructureMutation,
  useConfirmStudentModeByAdmissionAdminMutation,
  useRejectStudentModeByAdmissionAdminMutation,
  useGetReceiptByAdmissionQuery,
  useReceiptActionByAdmissionMutation,
  useReApplyReceiptByStudentMutation,
  useGetFeeReceiptDetailQuery,
  useGetDocumentByAdmissionQuery,
  useAddDocumentByAdmissionMutation,
  useUpdateDocumentByAdmissionMutation,
  useDeleteDocumentByAdmissionMutation,
  useRefundAmountByAdmissionAdminMutation,
  useGetRefundByAdmissionQuery,
  useUpdateRemarkByAdmissionAdminMutation,
  useExportFilterDataByAdmissionMutation,
  useGetAllExcelByAdmissionAdminQuery,
  usePayAdmissionFeeByStudentMutation,
  useUpdateExcelByAdmissionAdminMutation,
  useDeleteExcelByAdmissionAdminMutation,
  useUpdateDocumentByAdmissionAdminMutation,
  useDeleteDocumentByAdmissionAdminMutation,
  useAddModeratorByAdmissionAdminMutation,
  useGetModeratorByAdmissionAdminQuery,
  useUpdateModeratorByAdmissionAdminMutation,
  useDeleteModeratorByAdmissionAdminMutation,
  useAdmissionGetSiteInfoQuery,
  useAdmissionUpdateSiteInfoMutation,
  useGetScholarshipListAdmissionQuery,
  useAddScholarshipAdmissionMutation,
  useGetOneScholarshipAdmissionQuery,
  useGetOneScholarshipAllCandidateAdmissionQuery,
  useOneSchloarshipActionAdmissionMutation,
  useAddScholarshipFundCorpusAdmissionMutation,
  useGetScholarshipFundCorpusAdmissionQuery,
  useAddMoreScholarshipFundCorpusAdmissionMutation,
  useUpdateApplicationByAdmissionMutation,
  useDeleteApplicationByAdmissionMutation,
  useForgetPasswordProtectionMutation,
  usePasswordProtectionToggleMutation,
  usePasswordProtectionLoginMutation,
  useUpdateFeeStructureByAppliationWiseMutation,
  useGetRefundedListByAdmissionQuery,
  useDirectJoinFormWithPayAdmissionMutation,
  useCollectSetOffAdmissionFeesMutation,
  useAdmissionDocsActionByStudentMutation,
  useScholarShipExcelByAdmissionMutation,
  useScholarShipExcelByInstituteMutation,
  useAddScholarNumberAdmissionMutation,
  useStudentDepartmentFeesQuery,
  useStudentBacklogFeesQuery,
  useInternalFeeReceiptQuery,
  useDropAdmissionFeesCardByAdmissionMutation,
  useAllApplicationByAdmissionQuery,
  useAddNewFeesByAdmissionMutation,
  useCollectNewAddFeesByAdmissionMutation,
  useGovernmentCollectNewAddFeesByAdmissionMutation,
  useAdmissionReminderMutation,
  useAdmissionInstallmentEditFeesByAdmissionMutation,
  //
  useGetPendingCustomFilterByAdmissionQuery,
  useGetBatchStandardWithMultipleDepartmentMutation,

  useGetDailyCollectionByAdmissionQuery,

  //
  useEditStudentGrNumberMutation,

  //
  useAdmissionRevertBackSelectedToApplicationMutation,
  useAdmissionRevertBackDocsToSelectedMutation,
  useRemoveFeesInstallmentCardMutation,
  useTransferApplicatToOtherApplicationMutation,
  useExistStudentFeesExcelByAdmissionMutation,
  useStudentValidaForApplicationByAdmissionMutation,
  useStudentBankValidationByAdmissionMutation,
  useMarkCompleteToOngoingApplicationMutation,
  useGetReminderHistoryByAdmissionQuery,
  useGetOsReminderStudentListMutation,
  useStudentScholarshipNumberDublicateMutation,
} = admissionApiDynamic;
