import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";
import {
  baseUrl,
  deleteMethod,
  patchMethod,
  postMethod,
  putMethod,
  session,
} from "../BaseUrl";
import {
  classAddDisplayPersonFunction,
  classAllBatchWithClassFunction,
  classAllChecklistFunction,
  classAllComplaintFunction,
  classAllDepartmentWithBatchFunction,
  classAllFeesFunction,
  classAllHolidayFunction,
  classAllLeaveRequestFunction,
  classAllRequestStudentFunction,
  classAllStudentTransferFunction,
  classAllStudentFunction,
  classAllStudentFilterFunction,
  classAllSubjectCompleteFunction,
  classApproveStudentFunction,
  classChecklistAllStudentFunction,
  classCodeRefreshFunction,
  classComplaintSolveFunction,
  classCompleteFunction,
  classCoverPhotoFunction,
  classCreateStudentBehavourFunction,
  classOfflineExemptFeesFunction,
  classInfoUpdateFunction,
  classLeaveRequestActionFunction,
  classOneChecklistAssignFunction,
  classOneFeesDetailsFunction,
  classOneFeesFunction,
  classOneFeesSubmit,
  classProfileFunction,
  classProfilePhotoFunction,
  classPromoteStudentFunction,
  classRejectStudentFunction,
  classSettingFunction,
  classReportSettingFunction,
  classSettingReportFunction,
  classStudentAttendanceFunction,
  classStudentAttendanceUpdateFunction,
  classStudentBehavourFunction,
  classStudentCurrentAttendanceFunction,
  classStudentGraceFunction,
  classStudentReportCardAttendanceFunction,
  classStudentReportCardNecessaryFunction,
  classStudentReportCardFinalizeFunction,
  classStudentReportCardBeforeGraceFunction,
  classStudentReportCardFinalizeGraceFunction,
  classStudentReportCardFunction,
  classStudentTransferApprovedFunction,
  classStudentTransferRejectFunction,
  classComplaintDetailFunction,
  studentProfilePhotoFunction,
  studentFormEditFunction,
  studentClassRemoveFunction,
  classUnCompleteFunction,
  updateFeesByClassFunction,
  deleteFeesByClassFunction,
  allStudentFinalizeReportCardFunction,
  addUnapprovedStudentByClassFunction,
  classAllUnApprovedStudentFunction,
  getClassAllBatchFunction,
  getClassBatchAllStudentFunction,
  createClassBatchFunction,
  addClassStudentToBatchFunction,
  editClassBatchFunction,
  deleteClassBatchFunction,
  getDayTimetableFunction,
  addDayTimetableFunction,
  deleteClassBatchStudentFunction,
  removeDayTimetableFunction,
  classResuffleRearrangeFunction,
} from "./class_teacher_query_mutation_function";

export const classApi = createApi({
  reducerPath: "classApi",
  baseQuery: fetchBaseQuery({
    baseUrl: baseUrl,
    prepareHeaders: (headers) => {
      if (session()) {
        headers.set("authorization", session());
      }
      return headers;
    },
  }),
  endpoints: (builder) => ({
    classProfile: classProfileFunction(builder),
    classProfilePhoto: classProfilePhotoFunction(builder, patchMethod),
    classCoverPhoto: classCoverPhotoFunction(builder, patchMethod),
    classInfoUpdate: classInfoUpdateFunction(builder, postMethod),
    classAddDisplayPerson: classAddDisplayPersonFunction(builder, postMethod),
    classAllStudent: classAllStudentFunction(builder),
    classAllStudentFilter: classAllStudentFilterFunction(builder),
    classAllRequestStudent: classAllRequestStudentFunction(builder),
    classApproveStudent: classApproveStudentFunction(builder, postMethod),
    classRejectStudent: classRejectStudentFunction(builder, postMethod),
    classStudentCurrentAttendance:
      classStudentCurrentAttendanceFunction(builder),
    classStudentAttendance: classStudentAttendanceFunction(builder, postMethod),
    classStudentAttendanceUpdate: classStudentAttendanceUpdateFunction(
      builder,
      patchMethod
    ),
    classCodeRefresh: classCodeRefreshFunction(builder, patchMethod),
    classSetting: classSettingFunction(builder, patchMethod),
    classAllHoliday: classAllHolidayFunction(builder),
    classAllChecklist: classAllChecklistFunction(builder),
    classOneChecklistAssign: classOneChecklistAssignFunction(
      builder,
      patchMethod
    ),
    classChecklistAllStudent: classChecklistAllStudentFunction(builder),
    classStudentGrace: classStudentGraceFunction(builder, patchMethod),
    classReportSetting: classReportSettingFunction(builder, patchMethod),
    classSettingReport: classSettingReportFunction(builder),
    classStudentBehavour: classStudentBehavourFunction(builder),
    classCreateStudentBehavour: classCreateStudentBehavourFunction(
      builder,
      postMethod
    ),
    classStudentReportCard: classStudentReportCardFunction(builder),
    classStudentReportCardAttendance:
      classStudentReportCardAttendanceFunction(builder),
    classStudentReportCardNecessary:
      classStudentReportCardNecessaryFunction(builder),
    classStudentReportCardFinalize: classStudentReportCardFinalizeFunction(
      builder,
      postMethod
    ),
    classStudentReportCardFinalizeGrace:
      classStudentReportCardFinalizeGraceFunction(builder, patchMethod),
    classStudentReportCardBeforeGrace:
      classStudentReportCardBeforeGraceFunction(builder, patchMethod),
    classAllLeaveRequest: classAllLeaveRequestFunction(builder),
    classLeaveRequestAction: classLeaveRequestActionFunction(
      builder,
      patchMethod
    ),
    classAllComplaint: classAllComplaintFunction(builder),
    classComplaintDetail: classComplaintDetailFunction(builder),
    classComplaintSolve: classComplaintSolveFunction(builder, patchMethod),
    classAllStudentTransfer: classAllStudentTransferFunction(builder),
    classStudentTransferReject: classStudentTransferRejectFunction(
      builder,
      putMethod
    ),
    classStudentTransferApproved: classStudentTransferApprovedFunction(
      builder,
      patchMethod
    ),
    classAllFees: classAllFeesFunction(builder),
    classOneFees: classOneFeesFunction(builder),
    classOneFeesDetails: classOneFeesDetailsFunction(builder),
    classOfflineExemptedFees: classOfflineExemptFeesFunction(
      builder,
      postMethod
    ),
    classOneFeesSubmit: classOneFeesSubmit(builder, postMethod),
    classAllSubjectComplete: classAllSubjectCompleteFunction(builder),
    classAllDepartmentWithBatch: classAllDepartmentWithBatchFunction(builder),
    classAllBatchWithClass: classAllBatchWithClassFunction(builder),
    classPromoteStudent: classPromoteStudentFunction(builder, postMethod),
    classComplete: classCompleteFunction(builder, patchMethod),

    // for student form Edit
    studentProfilePhoto: studentProfilePhotoFunction(builder, patchMethod),
    studentFormEdit: studentFormEditFunction(builder, patchMethod),
    studentClassRemove: studentClassRemoveFunction(builder, patchMethod),
    classUnComplete: classUnCompleteFunction(builder, patchMethod),
    updateFeesByClass: updateFeesByClassFunction(builder, patchMethod),
    deleteFeesByClass: deleteFeesByClassFunction(builder, deleteMethod),
    allStudentFinalizeReportCard: allStudentFinalizeReportCardFunction(
      builder,
      postMethod
    ),
    addUnapprovedStudentByClass: addUnapprovedStudentByClassFunction(
      builder,
      postMethod
    ),
    classAllUnApprovedStudent: classAllUnApprovedStudentFunction(builder),

    getClassAllBatch: getClassAllBatchFunction(builder),
    getClassBatchAllStudent: getClassBatchAllStudentFunction(builder),
    createClassBatch: createClassBatchFunction(builder),
    addClassStudentToBatch: addClassStudentToBatchFunction(builder),
    editClassBatch: editClassBatchFunction(builder),
    deleteClassBatch: deleteClassBatchFunction(builder),
    getDayTimetable: getDayTimetableFunction(builder),
    addDayTimetable: addDayTimetableFunction(builder),
    removeDayTimetable: removeDayTimetableFunction(builder),
    deleteClassBatchStudent: deleteClassBatchStudentFunction(builder),
    classResuffleRearrange: classResuffleRearrangeFunction(builder),
  }),
});

export const {
  useClassProfileQuery,
  useClassProfilePhotoMutation,
  useClassCoverPhotoMutation,
  useClassInfoUpdateMutation,
  useClassAddDisplayPersonMutation,
  useClassAllStudentQuery,
  useClassAllStudentFilterQuery,
  useClassAllRequestStudentQuery,
  useClassApproveStudentMutation,
  useClassRejectStudentMutation,
  useClassStudentCurrentAttendanceQuery,
  useClassStudentAttendanceMutation,
  useClassStudentAttendanceUpdateMutation,
  useClassCodeRefreshMutation,
  useClassSettingMutation,
  useClassAllHolidayQuery,
  useClassAllChecklistQuery,
  useClassOneChecklistAssignMutation,
  useClassChecklistAllStudentQuery,
  useClassStudentGraceMutation,
  useClassReportSettingMutation,
  useClassSettingReportQuery,
  useClassStudentBehavourQuery,
  useClassCreateStudentBehavourMutation,
  useClassStudentReportCardQuery,
  useClassStudentReportCardAttendanceQuery,
  useClassStudentReportCardNecessaryQuery,
  useClassStudentReportCardFinalizeMutation,
  useClassStudentReportCardBeforeGraceMutation,
  useClassStudentReportCardFinalizeGraceMutation,
  useClassAllLeaveRequestQuery,
  useClassLeaveRequestActionMutation,
  useClassAllComplaintQuery,
  useClassComplaintDetailQuery,
  useClassComplaintSolveMutation,
  useClassAllStudentTransferQuery,
  useClassStudentTransferRejectMutation,
  useClassStudentTransferApprovedMutation,
  useClassAllFeesQuery,
  useClassOneFeesQuery,
  useClassOneFeesDetailsQuery,
  useClassOfflineExemptedFeesMutation,
  useClassOneFeesSubmitMutation,
  useClassAllSubjectCompleteQuery,
  useClassAllDepartmentWithBatchQuery,
  useClassAllBatchWithClassQuery,
  useClassPromoteStudentMutation,
  useClassCompleteMutation,
  useStudentProfilePhotoMutation,
  useStudentFormEditMutation,
  useStudentClassRemoveMutation,
  useClassUnCompleteMutation,
  useUpdateFeesByClassMutation,
  useDeleteFeesByClassMutation,
  useAllStudentFinalizeReportCardMutation,
  //
  useAddUnapprovedStudentByClassMutation,
  useClassAllUnApprovedStudentQuery,

  // for batch
  useGetClassAllBatchQuery,
  useGetClassBatchAllStudentQuery,
  useCreateClassBatchMutation,
  useAddClassStudentToBatchMutation,
  useEditClassBatchMutation,
  useDeleteClassBatchMutation,
  useGetDayTimetableQuery,
  useAddDayTimetableMutation,
  useDeleteClassBatchStudentMutation,
  useRemoveDayTimetableMutation,
  useClassResuffleRearrangeMutation,
} = classApi;
