import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";
import {
  baseUrl,
  deleteMethod,
  patchMethod,
  postMethod,
  session,
} from "../BaseUrl";
import {
  getActivatedMemberAccountFunction,
  departmentAddDisplayPersonFunction,
  departmentAllChecklistFunction,
  departmentAllClassMasterFunction,
  departmentAllComplaintFunction,
  departmentAllExamFunction,
  departmentAllFeesFunction,
  departmentAllHolidayFunction,
  departmentAllStaffFunction,
  departmentAllSubjectMasterFunction,
  departmentBatchAllClassFunction,
  departmentComplaintDetailFunction,
  departmentComplaintSolveFunction,
  departmentCoverPhotoFunction,
  departmentCreatedChecklistFunction,
  departmentCreatedHolidayFunction,
  departmentCreateExamFunction,
  departmentCreateFeesFunction,
  departmentDeleteHolidayFunction,
  departmentExamDetailFunction,
  departmentInfoUpdateFunction,
  departmentProfileFunction,
  departmentProfilePhotoFunction,
  departmentUpadateChecklistFunction,
  departmentElectionCreateFunction,
  departmentAllElectionFunction,
  departmentOneElectionFunction,
  departmentOneElectionAllCandidateFunction,
  departmentElectionActionFunction,
  departmentElectionSettingFunction,
  departmentBacklogClassMasterFunction,
  departmentBacklogSubjectMasterFunction,
  departmentBacklogSubjectAllStudentFunction,
  departmentBacklogSubjectAllStudentDropoutFunction,
  departmentBacklogOneStudentClearDropoutFunction,
  participateEventList,
  participateEventDetails,
  participateEventStudentList,
  assignChecklistToStudent,
  resultDeclaration,
  createParticipativeEvent,
  departmentGetSiteInfoFunction,
  departmentUpdateSiteInfoFunction,
  ///promote
  getInstituteDetailByPromoteFunction,
  getDepartmentDetailByPromoteFunction,
  getPromoteStudentByPromoteFunction,
  getNotPromoteStudentByPromoteFunction,
  getExaminationSectionDetailFunction,
  getClassListExamFunction,
  getSeatingListExamFunction,
  getOneSeatingExamFunction,
  destroyOneSeatingExamFunction,
  updateOneSeatingExamFunction,
  addSeatingExamFunction,
  getOneDepartmentBatchListFunction,
  withoutPaymentParticipateApplyFunction,
  createAutomateSeatingArrangementFunction,
  getAllExamFeeStructureFunction,
  updateExamFeeStructureFunction,
  examFeeStructureDetailFunction,
  createBacklogExamFunction,
  getBacklogExamListFunction,
  departmentAllClassMasterBacklogFunction,
  departmentAllSubjectMasterBacklogFunction,
  sendExamNotifyToSubjectFunction,
  createGradeSystemFunction,
  getAllUniversalGradeFunction,
  getOneGradeDetailFunction,
  //
  getMentorListFunction,
  addMentorDepartmentFunction,
  getOneMentorDetailFunction,
  getOneMentorMenteeListFunction,
  addNewMenteeFunction,
  removeMenteeFunction,
  getAllQueryListFunction,
  getQueryDetailFunction,
  markQueryFunction,
  getAllMentorClassListFunction,
  getClassStudentListFunction,
  addSeatingBacklogExamFunction,
  createBacklogAutomateSeatingArrangementFunction,
  updateGradeSystemFunction,
  departmentDeleteChecklistFunction,
  updateSubjectCourseCreditFunction,
  addMeetingByMentorFunction,
  getAllMeetingByMentorFunction,
  getOneMeetingDetailFunction,
  undoPromoteStudentFunction,
  createSubjectExamFunction,
  departmentCopoSettingUpdateFunction,
  getAllCertificateAuthorityFunction,
  certificateAuthorityActionFunction,
  updateCertificateAuthorityFundFunction,
  updateMutlipleLeaveConfigFunction,
  updateOneStaffLeaveConfigFunction,
  raiseLeaveRequestByStaffFunction,
  getManageCOffLeaveFunction,
  markCOffLeaveFunction,
  getLeaveOverviewCountFunction,
  getLeaveOverviewIssueFunction,
  getAllExcelByPromoteFunction,
  updateExcelByPromoteFunction,
  deleteExcelByPromoteFunction,
  exportPromoteStudentExcelFunction,
} from "./department_head_query_mutation_function";

export const departmentApi = createApi({
  reducerPath: "departmentApi",
  baseQuery: fetchBaseQuery({
    baseUrl: baseUrl,
    prepareHeaders: (headers) => {
      if (session()) {
        headers.set("authorization", session());
      }
      return headers;
    },
  }),
  endpoints: (builder) => ({
    getActivatedMemberAccount: getActivatedMemberAccountFunction(builder),
    departmentProfile: departmentProfileFunction(builder),
    departmentProfilePhoto: departmentProfilePhotoFunction(
      builder,
      patchMethod
    ),
    departmentCoverPhoto: departmentCoverPhotoFunction(builder, patchMethod),
    departmentInfoUpdate: departmentInfoUpdateFunction(builder, postMethod),
    departmentAddDisplayPerson: departmentAddDisplayPersonFunction(
      builder,
      postMethod
    ),
    departmentAllStaff: departmentAllStaffFunction(builder),
    departmentBatchAllClass: departmentBatchAllClassFunction(builder),
    departmentCreatedHoliday: departmentCreatedHolidayFunction(
      builder,
      postMethod
    ),
    departmentAllHoliday: departmentAllHolidayFunction(builder),
    departmentDeleteHoliday: departmentDeleteHolidayFunction(
      builder,
      deleteMethod
    ),
    departmentCreatedChecklist: departmentCreatedChecklistFunction(
      builder,
      postMethod
    ),
    departmentAllChecklist: departmentAllChecklistFunction(builder),
    departmentUpadateChecklist: departmentUpadateChecklistFunction(
      builder,
      patchMethod
    ),
    departmentAllClassMaster: departmentAllClassMasterFunction(builder),
    departmentAllSubjectMaster: departmentAllSubjectMasterFunction(builder),
    departmentCreateExam: departmentCreateExamFunction(builder, postMethod),
    departmentAllExam: departmentAllExamFunction(builder),
    departmentExamDetail: departmentExamDetailFunction(builder),
    departmentAllComplaint: departmentAllComplaintFunction(builder),
    departmentComplaintDetail: departmentComplaintDetailFunction(builder),
    departmentComplaintSolve: departmentComplaintSolveFunction(
      builder,
      patchMethod
    ),
    departmentAllFees: departmentAllFeesFunction(builder),
    departmentCreateFees: departmentCreateFeesFunction(builder, postMethod),
    departmentElectionCreate: departmentElectionCreateFunction(
      builder,
      postMethod
    ),
    departmentAllElection: departmentAllElectionFunction(builder),
    departmentOneElection: departmentOneElectionFunction(builder),
    departmentOneElectionAllCandidate:
      departmentOneElectionAllCandidateFunction(builder),
    departmentElectionAction: departmentElectionActionFunction(
      builder,
      patchMethod
    ),
    departmentElectionSetting: departmentElectionSettingFunction(
      builder,
      patchMethod
    ),

    departmentBacklogClassMaster: departmentBacklogClassMasterFunction(builder),
    departmentBacklogSubjectMaster:
      departmentBacklogSubjectMasterFunction(builder),
    departmentBacklogSubjectAllStudent:
      departmentBacklogSubjectAllStudentFunction(builder),
    departmentBacklogSubjectAllStudentDropout:
      departmentBacklogSubjectAllStudentDropoutFunction(builder),

    departmentBacklogOneStudentClearDropout:
      departmentBacklogOneStudentClearDropoutFunction(builder, patchMethod),
    participateEventList: participateEventList(builder),
    participateEventDetails: participateEventDetails(builder),
    participateEventStudentList: participateEventStudentList(builder),
    assignChecklistToStudent: assignChecklistToStudent(builder),
    resultDeclaration: resultDeclaration(builder),
    createParticipativeEvent: createParticipativeEvent(builder),
    departmentGetSiteInfo: departmentGetSiteInfoFunction(builder),
    departmentUpdateSiteInfo: departmentUpdateSiteInfoFunction(
      builder,
      patchMethod
    ),
    getInstituteDetailByPromote: getInstituteDetailByPromoteFunction(builder),
    getDepartmentDetailByPromote: getDepartmentDetailByPromoteFunction(builder),
    getPromoteStudentByPromote: getPromoteStudentByPromoteFunction(builder),
    getNotPromoteStudentByPromote:
      getNotPromoteStudentByPromoteFunction(builder),
    getExaminationSectionDetail: getExaminationSectionDetailFunction(builder),
    getClassListExam: getClassListExamFunction(builder),
    getSeatingListExam: getSeatingListExamFunction(builder),
    getOneSeatingExam: getOneSeatingExamFunction(builder),
    destroyOneSeatingExam: destroyOneSeatingExamFunction(builder, deleteMethod),
    updateOneSeatingExam: updateOneSeatingExamFunction(builder, patchMethod),
    addSeatingExam: addSeatingExamFunction(builder, postMethod),
    getOneDepartmentBatchList: getOneDepartmentBatchListFunction(builder),
    withoutPaymentParticipateApply: withoutPaymentParticipateApplyFunction(
      builder,
      patchMethod
    ),

    createAutomateSeatingArrangement: createAutomateSeatingArrangementFunction(
      builder,
      postMethod
    ),
    getAllExamFeeStructure: getAllExamFeeStructureFunction(builder),
    updateExamFeeStructure: updateExamFeeStructureFunction(
      builder,
      patchMethod
    ),
    examFeeStructureDetail: examFeeStructureDetailFunction(builder),
    createBacklogExam: createBacklogExamFunction(builder, postMethod),
    getBacklogExamList: getBacklogExamListFunction(builder),
    departmentAllClassMasterBacklog:
      departmentAllClassMasterBacklogFunction(builder),
    departmentAllSubjectMasterBacklog:
      departmentAllSubjectMasterBacklogFunction(builder),
    sendExamNotifyToSubject: sendExamNotifyToSubjectFunction(builder),
    createGradeSystem: createGradeSystemFunction(builder, postMethod),
    getAllUniversalGrade: getAllUniversalGradeFunction(builder),
    getOneGradeDetail: getOneGradeDetailFunction(builder),
    //
    getMentorList: getMentorListFunction(builder),
    addMentorDepartment: addMentorDepartmentFunction(builder, postMethod),
    getOneMentorDetail: getOneMentorDetailFunction(builder),
    getOneMentorMenteeList: getOneMentorMenteeListFunction(builder),
    addNewMentee: addNewMenteeFunction(builder, postMethod),
    removeMentee: removeMenteeFunction(builder, postMethod),
    getAllQueryList: getAllQueryListFunction(builder),
    getQueryDetail: getQueryDetailFunction(builder),
    markQuery: markQueryFunction(builder, patchMethod),
    getAllMentorClassList: getAllMentorClassListFunction(builder),
    getClassStudentList: getClassStudentListFunction(builder),
    addSeatingBacklogExam: addSeatingBacklogExamFunction(builder, postMethod),

    createBacklogAutomateSeatingArrangement:
      createBacklogAutomateSeatingArrangementFunction(builder, postMethod),

    updateGradeSystem: updateGradeSystemFunction(builder, patchMethod),
    departmentDeleteChecklist: departmentDeleteChecklistFunction(
      builder,
      deleteMethod
    ),
    updateSubjectCourseCredit: updateSubjectCourseCreditFunction(
      builder,
      patchMethod
    ),

    addMeetingByMentor: addMeetingByMentorFunction(builder, postMethod),
    getAllMeetingByMentor: getAllMeetingByMentorFunction(builder),
    getOneMeetingDetail: getOneMeetingDetailFunction(builder),
    undoPromoteStudent: undoPromoteStudentFunction(builder),
    createSubjectExam: createSubjectExamFunction(builder),
    departmentCopoSettingUpdate: departmentCopoSettingUpdateFunction(builder),

    getAllCertificateAuthority: getAllCertificateAuthorityFunction(builder),
    certificateAuthorityAction: certificateAuthorityActionFunction(builder),
    updateCertificateAuthorityFund:
      updateCertificateAuthorityFundFunction(builder),

    updateMutlipleLeaveConfig: updateMutlipleLeaveConfigFunction(builder),
    updateOneStaffLeaveConfig: updateOneStaffLeaveConfigFunction(builder),
    raiseLeaveRequestByStaff: raiseLeaveRequestByStaffFunction(builder),
    getManageCOffLeave: getManageCOffLeaveFunction(builder),
    markCOffLeave: markCOffLeaveFunction(builder),
    getLeaveOverviewCount: getLeaveOverviewCountFunction(builder),
    getLeaveOverviewIssue: getLeaveOverviewIssueFunction(builder),
    getAllExcelByPromote: getAllExcelByPromoteFunction(builder),
    updateExcelByPromote: updateExcelByPromoteFunction(builder),
    deleteExcelByPromote: deleteExcelByPromoteFunction(builder),
    exportPromoteStudentExcel: exportPromoteStudentExcelFunction(builder),
  }),
});

export const {
  useGetActivatedMemberAccountQuery,
  useCreateParticipativeEventMutation,
  useParticipateEventListQuery,
  useParticipateEventDetailsQuery,
  useAssignChecklistToStudentMutation,
  useResultDeclarationMutation,
  useParticipateEventStudentListQuery,
  useDepartmentProfileQuery,
  useDepartmentProfilePhotoMutation,
  useDepartmentCoverPhotoMutation,
  useDepartmentInfoUpdateMutation,
  useDepartmentAddDisplayPersonMutation,
  useDepartmentAllStaffQuery,
  useDepartmentBatchAllClassQuery,
  useDepartmentCreatedHolidayMutation,
  useDepartmentAllHolidayQuery,
  useDepartmentDeleteHolidayMutation,
  useDepartmentCreatedChecklistMutation,
  useDepartmentAllChecklistQuery,
  useDepartmentUpadateChecklistMutation,
  useDepartmentAllClassMasterQuery,
  useDepartmentAllSubjectMasterQuery,
  useDepartmentCreateExamMutation,
  useDepartmentAllExamQuery,
  useDepartmentExamDetailQuery,
  useDepartmentAllComplaintQuery,
  useDepartmentComplaintDetailQuery,
  useDepartmentComplaintSolveMutation,
  useDepartmentAllFeesQuery,
  useDepartmentCreateFeesMutation,
  useDepartmentElectionCreateMutation,
  useDepartmentAllElectionQuery,
  useDepartmentOneElectionQuery,
  useDepartmentOneElectionAllCandidateQuery,
  useDepartmentElectionActionMutation,
  useDepartmentElectionSettingMutation,
  useDepartmentBacklogClassMasterQuery,
  useDepartmentBacklogSubjectMasterQuery,
  useDepartmentBacklogSubjectAllStudentQuery,
  useDepartmentBacklogSubjectAllStudentDropoutQuery,
  useDepartmentBacklogOneStudentClearDropoutMutation,
  useDepartmentGetSiteInfoQuery,
  useDepartmentUpdateSiteInfoMutation,
  ////////
  useGetInstituteDetailByPromoteQuery,
  useGetDepartmentDetailByPromoteQuery,
  useGetPromoteStudentByPromoteQuery,
  useGetNotPromoteStudentByPromoteQuery,
  useGetExaminationSectionDetailQuery,
  /////////
  useGetClassListExamQuery,
  useGetSeatingListExamQuery,
  useGetOneSeatingExamQuery,
  useDestroyOneSeatingExamMutation,
  useUpdateOneSeatingExamMutation,
  useAddSeatingExamMutation,

  useGetOneDepartmentBatchListQuery,
  useWithoutPaymentParticipateApplyMutation,
  useCreateAutomateSeatingArrangementMutation,

  useGetAllExamFeeStructureQuery,
  useUpdateExamFeeStructureMutation,
  useExamFeeStructureDetailQuery,
  useCreateBacklogExamMutation,
  useGetBacklogExamListQuery,
  useDepartmentAllClassMasterBacklogQuery,
  useDepartmentAllSubjectMasterBacklogQuery,
  useSendExamNotifyToSubjectQuery,

  useCreateGradeSystemMutation,
  useGetAllUniversalGradeQuery,
  useGetOneGradeDetailQuery,
  //
  useGetMentorListQuery,
  useAddMentorDepartmentMutation,
  useGetOneMentorDetailQuery,
  useGetOneMentorMenteeListQuery,
  useAddNewMenteeMutation,
  useRemoveMenteeMutation,
  useGetAllQueryListQuery,
  useGetQueryDetailQuery,
  useMarkQueryMutation,
  useGetAllMentorClassListQuery,
  useGetClassStudentListQuery,

  useAddSeatingBacklogExamMutation,
  useCreateBacklogAutomateSeatingArrangementMutation,
  useUpdateGradeSystemMutation,
  useDepartmentDeleteChecklistMutation,
  useUpdateSubjectCourseCreditMutation,
  useAddMeetingByMentorMutation,
  useGetAllMeetingByMentorQuery,
  useGetOneMeetingDetailQuery,
  useUndoPromoteStudentMutation,
  useCreateSubjectExamMutation,
  useDepartmentCopoSettingUpdateMutation,
  useGetAllCertificateAuthorityQuery,
  useCertificateAuthorityActionMutation,
  useUpdateCertificateAuthorityFundMutation,
  useUpdateMutlipleLeaveConfigMutation,
  useUpdateOneStaffLeaveConfigMutation,
  useRaiseLeaveRequestByStaffMutation,
  useGetManageCOffLeaveQuery,
  useMarkCOffLeaveMutation,
  useGetLeaveOverviewCountQuery,
  useGetLeaveOverviewIssueQuery,
  useGetAllExcelByPromoteQuery,
  useUpdateExcelByPromoteMutation,
  useDeleteExcelByPromoteMutation,
  useExportPromoteStudentExcelMutation,
} = departmentApi;
