import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

import { baseUrl, prepareHeaders } from "./configApi";
import {
  activateFinance,
  editFinanceFunction,
  fetchFinance,
  uploadBank,
  uploadEditBank,
  removeBankDetail,
  paymentDetail,
  remainBalance,
  dueBalance,
  remainStudentList,
  submissionRequest,
  acceptQuery,
  rejectQuery,
  acceptArray,
  rejectArray,
  allIncome,
  allIBalance,
  oneIncome,
  addIncome,
  allExpense,
  allEBalance,
  oneExpense,
  addExpense,
  salHistory,
  oneEmpAndOneSalary,
  allEmp,
  allEmpStaff,
  addEmployeePayrollFunction,
  allHistoryFunction,
  addPayrollFunction,
  oneStaffAttendanceFunction,
  merchantIdFunction,
  inventoryListFunction,
  oneInventoryExpneseListFunction,
  getBankByFinanceFunction,
  paymentModeUpdateFinanceFunction,
  addBankByFinanceFunction,
  getAllFeesCategoryFunction,
  addFeesCategoryFunction,
  getAllFeesStructureFunction,
  addFeesStructureFunction,
  getAllExemptionFunction,
  getAllGovernmentScholarshipFunction,
  oneFeeStructureDetailFunction,
  allAdmissionFeeFinanceFunction,
  admissionFeeActionFinanceFunction,
  allLibraryFeeFinanceFunction,
  libraryFeeActionFinanceFunction,
  admissionGovernmentGrantFinanceFunction,
  getAllFeeHeadMasterFunction,
  addFeeHeadMasterFunction,
  updateFeeHeadMasterFunction,
  deleteFeesCategoryFunction,
  updateFeesStructureFunction,
  updateRetroFeesStructureFunction,
  deleteFeesStructureFunction,
  deleteFeesHeadFunction,
  addExcelCategoryByFinanceFunction,
  addExcelStructureByFinanceFunction,
  addExcelFeeHeadByFinanceFunction,
  filterTransactionHistoryFunction,
  getAllExcelByFinanceFunction,
  updateExcelByFinanceFunction,
  deleteExcelByFinanceFunction,
  getAllBankByFinanceFunction,
  updateBankByFinanceFunction,
  deleteBankByFinanceFunction,
  getOneBankByFinanceFunction,
  getMasterDepositByFinanceFunction,
  getMasterDepositAllByFinanceFunction,
  refundDepositByFinanceFunction,
  getAllDepositRefundByFinanceFunction,
  addModeratorByFinanceFunction,
  getModeratorByFinanceFunction,
  updateModeratorByFinanceFunction,
  deleteModeratorByFinanceFunction,
  filterFeeHeadReceiptFunction,
  getAllStandardInstituteFunction,
  getPayrollHeadListFunction,
  addPayrollHeadFunction,
  getOnePayrollHeadMonthFunction,
  getOnePayrollHeadEmployeeFunction,
  payrollAccountHeadPaymentFunction,
  allHostelFeeFinanceFunction,
  hostelFeeActionFinanceFunction,
  allTransportFeeFinanceFunction,
  transportFeeActionFinanceFunction,
  markAsSecondaryCategoryFunction,
  filterHostelFeeHeadReceiptFunction,
  financeTransportReceiptFunction,
} from "./financeAPIBuilder";

export const financeAPI = createApi({
  reducerPath: "financeAPI",
  baseQuery: fetchBaseQuery({ baseUrl, prepareHeaders: prepareHeaders }),
  endpoints: (builder) => ({
    activateFinanceHead: activateFinance(builder),
    editFinanceHead: editFinanceFunction(builder),
    fetchFinanceDetail: fetchFinance(builder),
    uploadFinanceBank: uploadBank(builder),
    financeEditBank: uploadEditBank(builder),
    financeRemoveBank: removeBankDetail(builder),
    getPaymentDetail: paymentDetail(builder),
    fetchFinanceRemainBalance: remainBalance(builder),
    fetchDueBalance: dueBalance(builder),
    remainingStudentFeeList: remainStudentList(builder),
    submissionRequestArray: submissionRequest(builder),
    acceptRequest: acceptQuery(builder),
    rejectRequest: rejectQuery(builder),
    acceptRequestArray: acceptArray(builder),
    rejectRequestArray: rejectArray(builder),
    getAllIncome: allIncome(builder),
    getAllIBalance: allIBalance(builder),
    oneIncomeDetail: oneIncome(builder),
    addIncomeData: addIncome(builder),
    getAllExpense: allExpense(builder),
    getAllEBalance: allEBalance(builder),
    oneExpenseDetail: oneExpense(builder),
    addExpenseData: addExpense(builder),
    getAllSalaryHistory: salHistory(builder),
    getOneEmpDetailAndOneSalaryHistory: oneEmpAndOneSalary(builder),
    getAllEmployee: allEmp(builder),
    getAllEmployeeStaff: allEmpStaff(builder),
    addEmployeePayroll: addEmployeePayrollFunction(builder),
    allHistory: allHistoryFunction(builder),
    addPayroll: addPayrollFunction(builder),
    oneStaffAttendance: oneStaffAttendanceFunction(builder),
    merchantId: merchantIdFunction(builder),
    inventoryList: inventoryListFunction(builder),
    oneInventoryExpneseList: oneInventoryExpneseListFunction(builder),
    getBankByFinance: getBankByFinanceFunction(builder),
    paymentModeUpdateFinance: paymentModeUpdateFinanceFunction(builder),
    addBankByFinance: addBankByFinanceFunction(builder),
    getAllFeesCategory: getAllFeesCategoryFunction(builder),
    addFeesCategory: addFeesCategoryFunction(builder),
    getAllFeesStructure: getAllFeesStructureFunction(builder),
    addFeesStructure: addFeesStructureFunction(builder),
    getAllExemption: getAllExemptionFunction(builder),
    getAllGovernmentScholarship: getAllGovernmentScholarshipFunction(builder),
    oneFeeStructureDetail: oneFeeStructureDetailFunction(builder),
    allAdmissionFeeFinance: allAdmissionFeeFinanceFunction(builder),
    admissionFeeActionFinance: admissionFeeActionFinanceFunction(builder),
    allLibraryFeeFinance: allLibraryFeeFinanceFunction(builder),
    libraryFeeActionFinance: libraryFeeActionFinanceFunction(builder),
    admissionGovernmentGrantFinance:
      admissionGovernmentGrantFinanceFunction(builder),
    getAllFeeHeadMaster: getAllFeeHeadMasterFunction(builder),
    addFeeHeadMaster: addFeeHeadMasterFunction(builder),
    updateFeeHeadMaster: updateFeeHeadMasterFunction(builder),
    deleteFeesCategory: deleteFeesCategoryFunction(builder),
    updateFeesStructure: updateFeesStructureFunction(builder),
    updateRetroFeesStructure: updateRetroFeesStructureFunction(builder),
    deleteFeesStructure: deleteFeesStructureFunction(builder),
    deleteFeesHead: deleteFeesHeadFunction(builder),
    addExcelCategoryByFinance: addExcelCategoryByFinanceFunction(builder),
    addExcelStructureByFinance: addExcelStructureByFinanceFunction(builder),
    addExcelFeeHeadByFinance: addExcelFeeHeadByFinanceFunction(builder),
    filterTransactionHistory: filterTransactionHistoryFunction(builder),
    getAllExcelByFinance: getAllExcelByFinanceFunction(builder),
    updateExcelByFinance: updateExcelByFinanceFunction(builder),
    deleteExcelByFinance: deleteExcelByFinanceFunction(builder),
    getAllBankByFinance: getAllBankByFinanceFunction(builder),
    deleteBankByFinance: deleteBankByFinanceFunction(builder),
    updateBankByFinance: updateBankByFinanceFunction(builder),
    getOneBankByFinance: getOneBankByFinanceFunction(builder),

    getMasterDepositByFinance: getMasterDepositByFinanceFunction(builder),
    getMasterDepositAllByFinance: getMasterDepositAllByFinanceFunction(builder),
    refundDepositByFinance: refundDepositByFinanceFunction(builder),
    getAllDepositRefundByFinance: getAllDepositRefundByFinanceFunction(builder),
    addModeratorByFinance: addModeratorByFinanceFunction(builder),
    getModeratorByFinance: getModeratorByFinanceFunction(builder),
    updateModeratorByFinance: updateModeratorByFinanceFunction(builder),
    deleteModeratorByFinance: deleteModeratorByFinanceFunction(builder),
    filterFeeHeadReceipt: filterFeeHeadReceiptFunction(builder),
    getAllStandardInstitute: getAllStandardInstituteFunction(builder),
    getPayrollHeadList: getPayrollHeadListFunction(builder),
    addPayrollHead: addPayrollHeadFunction(builder),
    getOnePayrollHeadMonth: getOnePayrollHeadMonthFunction(builder),
    getOnePayrollHeadEmployee: getOnePayrollHeadEmployeeFunction(builder),
    payrollAccountHeadPayment: payrollAccountHeadPaymentFunction(builder),
    allHostelFeeFinance: allHostelFeeFinanceFunction(builder),
    hostelFeeActionFinance: hostelFeeActionFinanceFunction(builder),

    allTransportFeeFinance: allTransportFeeFinanceFunction(builder),
    transportFeeActionFinance: transportFeeActionFinanceFunction(builder),
    markAsSecondaryCategory: markAsSecondaryCategoryFunction(builder),
    filterHostelFeeHeadReceipt: filterHostelFeeHeadReceiptFunction(builder),
    financeTransportReceipt: financeTransportReceiptFunction(builder),
  }),
});

export const {
  useActivateFinanceHeadMutation,
  useEditFinanceHeadMutation,
  useFetchFinanceDetailQuery,
  useUploadFinanceBankMutation,
  useFinanceEditBankMutation,
  useFinanceRemoveBankMutation,
  useGetPaymentDetailQuery,
  useFetchFinanceRemainBalanceQuery,
  useFetchDueBalanceQuery,
  useRemainingStudentFeeListQuery,
  useSubmissionRequestArrayQuery,
  useAcceptRequestMutation,
  useRejectRequestMutation,
  useAcceptRequestArrayQuery,
  useRejectRequestArrayQuery,
  useGetAllIncomeQuery,
  useGetAllIBalanceQuery,
  useOneIncomeDetailQuery,
  useAddIncomeDataMutation,
  useGetAllExpenseQuery,
  useGetAllEBalanceQuery,
  useOneExpenseDetailQuery,
  useAddExpenseDataMutation,
  useGetAllSalaryHistoryQuery,
  useGetOneEmpDetailAndOneSalaryHistoryQuery,
  useGetAllEmployeeQuery,
  useGetAllEmployeeStaffQuery,
  useAddEmployeePayrollMutation,
  useAllHistoryQuery,
  useAddPayrollMutation,
  useOneStaffAttendanceQuery,
  useMerchantIdQuery,
  useInventoryListQuery,
  useOneInventoryExpneseListQuery,
  useGetBankByFinanceQuery,
  usePaymentModeUpdateFinanceMutation,
  useAddBankByFinanceMutation,
  useGetAllFeesCategoryQuery,
  useAddFeesCategoryMutation,
  useGetAllFeesStructureQuery,
  useAddFeesStructureMutation,
  useGetAllExemptionQuery,
  useGetAllGovernmentScholarshipQuery,
  useOneFeeStructureDetailQuery,
  useAllAdmissionFeeFinanceQuery,
  useAdmissionFeeActionFinanceMutation,
  useAllLibraryFeeFinanceQuery,
  useLibraryFeeActionFinanceMutation,
  useAdmissionGovernmentGrantFinanceMutation,
  useGetAllFeeHeadMasterQuery,
  useAddFeeHeadMasterMutation,
  useUpdateFeeHeadMasterMutation,
  useDeleteFeesCategoryMutation,
  useUpdateFeesStructureMutation,
  useUpdateRetroFeesStructureMutation,
  useDeleteFeesStructureMutation,
  useDeleteFeesHeadMutation,
  useAddExcelCategoryByFinanceMutation,
  useAddExcelStructureByFinanceMutation,
  useAddExcelFeeHeadByFinanceMutation,
  useFilterTransactionHistoryQuery,
  useGetAllExcelByFinanceQuery,
  useUpdateExcelByFinanceMutation,
  useDeleteExcelByFinanceMutation,

  useGetAllBankByFinanceQuery,
  useDeleteBankByFinanceMutation,
  useUpdateBankByFinanceMutation,
  useGetOneBankByFinanceQuery,

  useGetMasterDepositByFinanceQuery,
  useGetMasterDepositAllByFinanceQuery,
  useRefundDepositByFinanceMutation,
  useGetAllDepositRefundByFinanceQuery,
  useAddModeratorByFinanceMutation,
  useGetModeratorByFinanceQuery,
  useUpdateModeratorByFinanceMutation,
  useDeleteModeratorByFinanceMutation,
  useFilterFeeHeadReceiptMutation,
  useGetAllStandardInstituteQuery,

  useGetPayrollHeadListQuery,
  useAddPayrollHeadMutation,
  useGetOnePayrollHeadMonthQuery,
  useGetOnePayrollHeadEmployeeQuery,
  usePayrollAccountHeadPaymentMutation,

  useAllHostelFeeFinanceQuery,
  useHostelFeeActionFinanceMutation,

  useAllTransportFeeFinanceQuery,
  useTransportFeeActionFinanceMutation,
  useMarkAsSecondaryCategoryMutation,
  useFilterHostelFeeHeadReceiptQuery,
  useFinanceTransportReceiptQuery,
} = financeAPI;
