import {
  donotFunction,
  financeAllBankFunction,
  financeBankDetailFilterFunction,
  financeExpenseBalanceFunction,
  financeExpenseDetailFunction,
  financeExpenseFunction,
  financeFeeListFunction,
  financeIncomeBalanceFunction,
  financeIncomeDetailFunction,
  financeIncomeFunction,
  financeDashboardMasterFunction,
  financeOneBankDetailFunction,
  financeReceiptFunction,
  financeRemainBalanceFunction,
  financeTransportReceiptFunction,
  financeDeleteFeesHeadFunction,
  financeAllFeeHeadMasterFunction,
  financeAddFeeHeadMasterFunction,
  financeUpdateFeeHeadMasterFunction,
  financeDeleteFeesCategoryFunction,
  financeUpdateFeesStructureFunction,
  financeUpdateRetroFeesStructureFunction,
  financeDeleteFeesStructureFunction,
  financeAllExcelFunction,
  financeUpdateExcelFunction,
  financeDeleteExcelFunction,
  financeAddBankFunction,
  financeUpdateBankFunction,
  financeDeleteBankFunction,
  financeMasterDepositFunction,
  financeMasterDepositAllFunction,
  financeMarkRefundDepositFunction,
  financeAllDepositRefundFunction,
  financeAddModeratorFunction,
  financeModeratorFunction,
  financeUpdateModeratorFunction,
  financeDeleteModeratorFunction,
  financeMarkAsSecondaryCategoryFunction,
  financeAddFeesStructureFunction,
  financeFeeStructureDetailFunction,
  financeAddIncomeFunction,
  financeAddExpenseFunction,
  financeAllExemptionFunction,
  financeAllSettlementFunction,
  financeAllTransactionFunction,
  financeAllFeesCategoryFunction,
  financeAddFeesCategoryFunction,
  financeAddExcelCategoryFunction,
  financeAddExcelStructureFunction,
  financeAddExcelFeeHeadFunction,
  financeStudentStatiticsFunction,
  financeAllInternalFeeFunction,
  financeAddInternalFeesFunction,
  instituteAllDepartmentFunction,
  financeStudentStatisticsExportFunction,
  financeFeeStatiticsFunction,
  financeAllFeeStructureFunction,
  financeOverallFeeStatisticsFunction,
  oneStudentProfileFunction,
  oneStudentFeesStatFunction,
  oneStudentAdmissionFeesFunction,
  oneStudentInternalFeesFunction,
  financeSendAllStudentMessageFunction,
  financeSendOneStudentMessageFunction,
  financeAllStudentMessageHistoryFunction,
  financeStudentGrChangeFunction,
  financeAddScholarNumberFunction,
  financeDropStudentOneAdmissionFeesFunction,
  financeUpdateStudentFeeStructureFunction,
  financeAllotScholarshipExcelFunction,
  financeAllotScholarshipFunction,
  financeAllotScholarshipNewAddFeesFunction,
  financeAdmissionStaticsFunction,

  //
  universalPlateformUserFunction,
  departmentBatchAllClassMasterFunction,
  departmentAllBatchFunction,
  instituteAllStaffFunction,
  instituteAllStudentFunction,
  departmentAllClassMasterFunction,
  userAllStatsFunction,
  instituteAllStudentIdListFunction,
} from "./finance_manager_query_mutation_function";

import { financeManagerApi } from "./financeManagerApi";

const financeManagerApiDynamic = financeManagerApi.injectEndpoints({
  endpoints: (builder) => ({
    financeDashboardMaster: financeDashboardMasterFunction(builder),
    financeBankDetailFilter: financeBankDetailFilterFunction(builder),
    donot: donotFunction(builder),
    financeIncome: financeIncomeFunction(builder),
    financeIncomeBalance: financeIncomeBalanceFunction(builder),
    financeIncomeDetail: financeIncomeDetailFunction(builder),
    financeExpense: financeExpenseFunction(builder),
    financeExpenseBalance: financeExpenseBalanceFunction(builder),
    financeExpenseDetail: financeExpenseDetailFunction(builder),
    financeRemainBalance: financeRemainBalanceFunction(builder),
    financeFeeList: financeFeeListFunction(builder),
    financeAllBank: financeAllBankFunction(builder),
    financeOneBankDetail: financeOneBankDetailFunction(builder),
    financeTransportReceipt: financeTransportReceiptFunction(builder),
    financeReceipt: financeReceiptFunction(builder),

    financeAllFeeHeadMaster: financeAllFeeHeadMasterFunction(builder),
    financeAddFeeHeadMaster: financeAddFeeHeadMasterFunction(builder),
    financeUpdateFeeHeadMaster: financeUpdateFeeHeadMasterFunction(builder),
    financeDeleteFeesCategory: financeDeleteFeesCategoryFunction(builder),
    financeAddFeesStructure: financeAddFeesStructureFunction(builder),
    financeFeeStructureDetail: financeFeeStructureDetailFunction(builder),
    financeUpdateFeesStructure: financeUpdateFeesStructureFunction(builder),
    financeUpdateRetroFeesStructure:
      financeUpdateRetroFeesStructureFunction(builder),
    financeDeleteFeesStructure: financeDeleteFeesStructureFunction(builder),
    financeDeleteFeesHead: financeDeleteFeesHeadFunction(builder),
    financeAllExcel: financeAllExcelFunction(builder),
    financeUpdateExcel: financeUpdateExcelFunction(builder),
    financeDeleteExcel: financeDeleteExcelFunction(builder),
    financeAddBank: financeAddBankFunction(builder),
    financeUpdateBank: financeUpdateBankFunction(builder),
    financeDeleteBank: financeDeleteBankFunction(builder),
    financeMasterDeposit: financeMasterDepositFunction(builder),
    financeMasterDepositAll: financeMasterDepositAllFunction(builder),
    financeMarkRefundDeposit: financeMarkRefundDepositFunction(builder),
    financeAllDepositRefund: financeAllDepositRefundFunction(builder),
    financeAddModerator: financeAddModeratorFunction(builder),
    financeModerator: financeModeratorFunction(builder),
    financeUpdateModerator: financeUpdateModeratorFunction(builder),
    financeDeleteModerator: financeDeleteModeratorFunction(builder),
    financeMarkAsSecondaryCategory:
      financeMarkAsSecondaryCategoryFunction(builder),
    financeAllExemption: financeAllExemptionFunction(builder),
    financeAddIncome: financeAddIncomeFunction(builder),
    financeAddExpense: financeAddExpenseFunction(builder),
    financeAllSettlement: financeAllSettlementFunction(builder),
    financeAllTransaction: financeAllTransactionFunction(builder),

    financeAllFeesCategory: financeAllFeesCategoryFunction(builder),
    financeAddFeesCategory: financeAddFeesCategoryFunction(builder),
    financeAddExcelCategory: financeAddExcelCategoryFunction(builder),
    financeAddExcelStructure: financeAddExcelStructureFunction(builder),
    financeAddExcelFeeHead: financeAddExcelFeeHeadFunction(builder),
    financeStudentStatitics: financeStudentStatiticsFunction(builder),
    financeAllInternalFee: financeAllInternalFeeFunction(builder),
    financeAddInternalFees: financeAddInternalFeesFunction(builder),
    instituteAllDepartment: instituteAllDepartmentFunction(builder),
    financeStudentStatisticsExport:
      financeStudentStatisticsExportFunction(builder),
    financeFeeStatitics: financeFeeStatiticsFunction(builder),
    financeAllFeeStructure: financeAllFeeStructureFunction(builder),
    financeOverallFeeStatistics: financeOverallFeeStatisticsFunction(builder),
    oneStudentProfile: oneStudentProfileFunction(builder),

    oneStudentFeesStat: oneStudentFeesStatFunction(builder),
    oneStudentAdmissionFees: oneStudentAdmissionFeesFunction(builder),
    oneStudentInternalFees: oneStudentInternalFeesFunction(builder),
    financeSendAllStudentMessage: financeSendAllStudentMessageFunction(builder),
    financeSendOneStudentMessage: financeSendOneStudentMessageFunction(builder),
    financeAllStudentMessageHistory:
      financeAllStudentMessageHistoryFunction(builder),
    financeStudentGrChange: financeStudentGrChangeFunction(builder),
    financeAddScholarNumber: financeAddScholarNumberFunction(builder),
    financeDropStudentOneAdmissionFees:
      financeDropStudentOneAdmissionFeesFunction(builder),
    financeUpdateStudentFeeStructure:
      financeUpdateStudentFeeStructureFunction(builder),

    financeAllotScholarshipExcel: financeAllotScholarshipExcelFunction(builder),

    financeAllotScholarship: financeAllotScholarshipFunction(builder),
    financeAllotScholarshipNewAddFees:
      financeAllotScholarshipNewAddFeesFunction(builder),

    financeAdmissionStatics: financeAdmissionStaticsFunction(builder),

    //
    departmentBatchAllClassMaster:
      departmentBatchAllClassMasterFunction(builder),
    universalPlateformUser: universalPlateformUserFunction(builder),
    departmentAllBatch: departmentAllBatchFunction(builder),
    instituteAllStaff: instituteAllStaffFunction(builder),
    instituteAllStudent: instituteAllStudentFunction(builder),
    departmentAllClassMaster: departmentAllClassMasterFunction(builder),
    userAllStats: userAllStatsFunction(builder),
    instituteAllStudentIdList: instituteAllStudentIdListFunction(builder),
  }),
});

export const {
  useFinanceDashboardMasterQuery,
  useFinanceBankDetailFilterQuery,
  useDonotQuery,
  useFinanceIncomeQuery,
  useFinanceIncomeBalanceQuery,
  useFinanceIncomeDetailQuery,
  useFinanceExpenseQuery,
  useFinanceExpenseBalanceQuery,
  useFinanceExpenseDetailQuery,
  useFinanceRemainBalanceQuery,
  useFinanceFeeListQuery,
  useFinanceAllBankQuery,
  useFinanceOneBankDetailQuery,
  useFinanceTransportReceiptQuery,
  useFinanceReceiptQuery,
  //
  useFinanceAllFeeHeadMasterQuery,
  useFinanceAddFeeHeadMasterMutation,
  useFinanceUpdateFeeHeadMasterMutation,
  useFinanceDeleteFeesCategoryMutation,
  useFinanceAddFeesStructureMutation,
  useFinanceFeeStructureDetailQuery,
  useFinanceUpdateFeesStructureMutation,
  useFinanceUpdateRetroFeesStructureMutation,
  useFinanceDeleteFeesStructureMutation,
  useFinanceDeleteFeesHeadMutation,
  useFinanceAllExcelQuery,
  useFinanceUpdateExcelMutation,
  useFinanceDeleteExcelMutation,
  useFinanceAddBankMutation,
  useFinanceUpdateBankMutation,
  useFinanceDeleteBankMutation,
  useFinanceMasterDepositQuery,
  useFinanceMasterDepositAllQuery,
  useFinanceMarkRefundDepositMutation,
  useFinanceAllDepositRefundQuery,
  useFinanceAddModeratorMutation,
  useFinanceModeratorQuery,
  useFinanceUpdateModeratorMutation,
  useFinanceDeleteModeratorMutation,
  useFinanceMarkAsSecondaryCategoryMutation,
  useFinanceAllExemptionQuery,
  useFinanceAddIncomeMutation,
  useFinanceAddExpenseMutation,
  useFinanceAllSettlementQuery,
  useFinanceAllTransactionQuery,
  useFinanceAllFeesCategoryQuery,
  useFinanceAddFeesCategoryMutation,
  useFinanceAddExcelCategoryMutation,
  useFinanceAddExcelStructureMutation,
  useFinanceAddExcelFeeHeadMutation,
  useFinanceStudentStatiticsMutation,
  useFinanceAllInternalFeeQuery,
  useFinanceAddInternalFeesMutation,
  useInstituteAllDepartmentQuery,
  useFinanceStudentStatisticsExportMutation,
  useFinanceFeeStatiticsMutation,
  useFinanceAllFeeStructureQuery,
  useFinanceOverallFeeStatisticsQuery,
  useOneStudentProfileQuery,
  useOneStudentFeesStatQuery,
  useOneStudentAdmissionFeesQuery,
  useOneStudentInternalFeesQuery,
  useFinanceSendAllStudentMessageMutation,
  useFinanceSendOneStudentMessageMutation,
  useFinanceAllStudentMessageHistoryQuery,
  useFinanceStudentGrChangeMutation,
  useFinanceAddScholarNumberMutation,
  useFinanceDropStudentOneAdmissionFeesMutation,
  useFinanceUpdateStudentFeeStructureMutation,
  useFinanceAllotScholarshipExcelMutation,
  useFinanceAllotScholarshipMutation,
  useFinanceAllotScholarshipNewAddFeesMutation,
  useFinanceAdmissionStaticsQuery,
  //

  useDepartmentBatchAllClassMasterQuery,
  useUniversalPlateformUserQuery,
  useDepartmentAllBatchQuery,
  useInstituteAllStaffQuery,
  useInstituteAllStudentQuery,
  useDepartmentAllClassMasterQuery,
  useUserAllStatsQuery,
  useInstituteAllStudentIdListQuery,
} = financeManagerApiDynamic;
