import { hostelApi } from "./hostelApi";
import {
  getHostelHostelitesListFunction,
  getHostelUnitListFunction,
  getHostelWardenListFunction,
  hostelActivateFunction,
  hostelCoverUploadFunction,
  hostelDetailFunction,
  hostelEidtActivateFunction,
  hostelRoomCoverUploadFunction,
  hostelUnitCoverUploadFunction,
  getHostelFeeStructureListFunction,
  addHostelUnitFunction,
  getHostelUnitDetailFunction,
  addRoomHostelUnitFunction,
  getRoomListHostelUnitFunction,
  getRoomDetailHostelFunction,
  getHostelRulesFunction,
  addHostelRulesFunction,
  editHostelRulesFunction,
  getHostelFormFunction,
  updateHostelFormFunction,
  getHostelApplyApplicationListFunction,
  userApplyHostelFunction,
  createHostelApplicationFunction,
  getApplicationRequestedListFunction,
  getApplicationSelectedListFunction,
  getApplicationConfirmListFunction,
  getOngoingApplicationListFunction,
  getCompletedApplicationListFunction,
  cancelApplicantRequestByHostelFunction,
  acceptApplicantRequestByHostelFunction,
  getHostelAppliciontDetailFunction,
  completeHostelApplicationFunction,
  confirmStudentModeByHostelFunction,
  rejectStudentModeByHostelFunction,
  editStructureByHostelFunction,
  collectStudentFeesByHostelFunction,
  refundStudentFeesByHostelFunction,
  allotBedByHostelFunction,
  applicantHostelRemainingFeeFuntcion,
  refundAmountByHostelFunction,
  getStudentRoommateListFunction,
  cancelHostelApplicationByStudentFunction,
  confirmHostelApplicationByStudentFunction,
  getAnnouncementListByHostelFunction,
  addAnnouncementByHostelFunction,
  getReceiptListByHostelFunction,
  oneReceiptActionByHostelFunction,
  getPendingFeeByHostelFunction,
  oneReceiptReApplyByStudentFunction,
  paymentOfflineFeeHostelByStudentFunction,
  submitCashToFinanceByHostelFunction,
  addHostilesExcelByHostelFunction,
  getRenewalApplicationListByHostelFunction,
  getRenewalSelectListByHostelFunction,
  getRenewalRenewedListByHostelFunction,
  getRenewalAllotListByHostelFunction,
  getRenewalCancelListByHostelFunction,
  getRenewalListByStudentFunction,
  selectRenewalByHostelFunction,
  cancelRenewalByHostelFunction,
  selectRenewalByStudentFunction,
  cancelRenewalByStudentFunction,
  collectRenewalFeeByHostelFunction,
  renewalAllotBedByHostelFunction,
  cancelConfirmRenewalByHostelFunction,
  hostelGetSiteInfoFunction,
  hostelUpdateSiteInfoFunction,
  addModeratorByHostelFunction,
  getModeratorByHostelFunction,
  updateModeratorByHostelFunction,
  deleteModeratorByHostelFunction,
  getMasterDepositByHostelFunction,
  getAllDepositRefundByHostelFunction,
  hostelExportApplicantApplicatonFunction,
  getAllExcelByHostelManagerFunction,
  updateExcelByHostelManagerFunction,
  deleteExcelByHostelManagerFunction,

  // batch functionality
  getHostelAllBatchFunction,
  createHostelBatchFunction,
  selectHostelBatchFunction,
  editHostelBatchFunction,
  deleteHostelBatchFunction,

  //
  getHostelAllStandardFunction,
  createHostelStandardFunction,
  deleteApplicationByHostelFunction,
  exportFilterDataByHostelFuction,
  getHostelLinkedListFunction,
  addHostelLinkedInstituteFunction,
} from "./hostel_query_mutation_function";

export const hostelApiDynamic = hostelApi.injectEndpoints({
  endpoints: (builder) => ({
    hostelDetail: hostelDetailFunction(builder),
    hostelActivate: hostelActivateFunction(builder),
    hostelEidtActivate: hostelEidtActivateFunction(builder),
    hostelCoverUpload: hostelCoverUploadFunction(builder),
    hostelUnitCoverUpload: hostelUnitCoverUploadFunction(builder),
    hostelRoomCoverUpload: hostelRoomCoverUploadFunction(builder),
    getHostelFeeStructureList: getHostelFeeStructureListFunction(builder),
    getHostelWardenList: getHostelWardenListFunction(builder),
    getHostelUnitList: getHostelUnitListFunction(builder),
    getHostelHostelitesList: getHostelHostelitesListFunction(builder),
    addHostelUnit: addHostelUnitFunction(builder),
    getHostelUnitDetail: getHostelUnitDetailFunction(builder),
    addRoomHostelUnit: addRoomHostelUnitFunction(builder),
    getRoomListHostelUnit: getRoomListHostelUnitFunction(builder),
    getRoomDetailHostel: getRoomDetailHostelFunction(builder),
    getHostelRules: getHostelRulesFunction(builder),
    addHostelRules: addHostelRulesFunction(builder),
    editHostelRules: editHostelRulesFunction(builder),
    getHostelForm: getHostelFormFunction(builder),
    updateHostelForm: updateHostelFormFunction(builder),
    getHostelApplyApplicationList:
      getHostelApplyApplicationListFunction(builder),
    userApplyHostel: userApplyHostelFunction(builder),
    createHostelApplication: createHostelApplicationFunction(builder),
    getApplicationRequestedList: getApplicationRequestedListFunction(builder),
    getApplicationSelectedList: getApplicationSelectedListFunction(builder),
    getApplicationConfirmList: getApplicationConfirmListFunction(builder),
    getOngoingApplicationList: getOngoingApplicationListFunction(builder),
    getCompletedApplicationList: getCompletedApplicationListFunction(builder),
    cancelApplicantRequestByHostel:
      cancelApplicantRequestByHostelFunction(builder),
    acceptApplicantRequestByHostel:
      acceptApplicantRequestByHostelFunction(builder),
    getHostelAppliciontDetail: getHostelAppliciontDetailFunction(builder),
    completeHostelApplication: completeHostelApplicationFunction(builder),
    confirmStudentModeByHostel: confirmStudentModeByHostelFunction(builder),
    rejectStudentModeByHostel: rejectStudentModeByHostelFunction(builder),
    editStructureByHostel: editStructureByHostelFunction(builder),
    collectStudentFeesByHostel: collectStudentFeesByHostelFunction(builder),
    refundStudentFeesByHostel: refundStudentFeesByHostelFunction(builder),
    allotBedByHostel: allotBedByHostelFunction(builder),
    applicantHostelRemainingFee: applicantHostelRemainingFeeFuntcion(builder),
    refundAmountByHostel: refundAmountByHostelFunction(builder),
    getStudentRoommateList: getStudentRoommateListFunction(builder),
    confirmHostelApplicationByStudent:
      confirmHostelApplicationByStudentFunction(builder),
    cancelHostelApplicationByStudent:
      cancelHostelApplicationByStudentFunction(builder),
    getAnnouncementListByHostel: getAnnouncementListByHostelFunction(builder),
    addAnnouncementByHostel: addAnnouncementByHostelFunction(builder),

    getReceiptListByHostel: getReceiptListByHostelFunction(builder),
    oneReceiptActionByHostel: oneReceiptActionByHostelFunction(builder),
    getPendingFeeByHostel: getPendingFeeByHostelFunction(builder),
    oneReceiptReApplyByStudent: oneReceiptReApplyByStudentFunction(builder),
    paymentOfflineFeeHostelByStudent:
      paymentOfflineFeeHostelByStudentFunction(builder),
    submitCashToFinanceByHostel: submitCashToFinanceByHostelFunction(builder),
    addHostilesExcelByHostel: addHostilesExcelByHostelFunction(builder),

    getRenewalApplicationListByHostel:
      getRenewalApplicationListByHostelFunction(builder),
    getRenewalSelectListByHostel: getRenewalSelectListByHostelFunction(builder),
    getRenewalRenewedListByHostel:
      getRenewalRenewedListByHostelFunction(builder),
    getRenewalAllotListByHostel: getRenewalAllotListByHostelFunction(builder),
    getRenewalCancelListByHostel: getRenewalCancelListByHostelFunction(builder),
    getRenewalListByStudent: getRenewalListByStudentFunction(builder),
    selectRenewalByHostel: selectRenewalByHostelFunction(builder),
    cancelRenewalByHostel: cancelRenewalByHostelFunction(builder),
    selectRenewalByStudent: selectRenewalByStudentFunction(builder),
    cancelRenewalByStudent: cancelRenewalByStudentFunction(builder),
    collectRenewalFeeByHostel: collectRenewalFeeByHostelFunction(builder),
    renewalAllotBedByHostel: renewalAllotBedByHostelFunction(builder),
    cancelConfirmRenewalByHostel: cancelConfirmRenewalByHostelFunction(builder),
    hostelGetSiteInfo: hostelGetSiteInfoFunction(builder),
    hostelUpdateSiteInfo: hostelUpdateSiteInfoFunction(builder),
    addModeratorByHostel: addModeratorByHostelFunction(builder),
    getModeratorByHostel: getModeratorByHostelFunction(builder),
    updateModeratorByHostel: updateModeratorByHostelFunction(builder),
    deleteModeratorByHostel: deleteModeratorByHostelFunction(builder),
    getMasterDepositByHostel: getMasterDepositByHostelFunction(builder),
    getAllDepositRefundByHostel: getAllDepositRefundByHostelFunction(builder),
    hostelExportApplicantApplicaton:
      hostelExportApplicantApplicatonFunction(builder),

    getAllExcelByHostelManager: getAllExcelByHostelManagerFunction(builder),
    updateExcelByHostelManager: updateExcelByHostelManagerFunction(builder),
    deleteExcelByHostelManager: deleteExcelByHostelManagerFunction(builder),

    getHostelAllBatch: getHostelAllBatchFunction(builder),
    createHostelBatch: createHostelBatchFunction(builder),
    selectHostelBatch: selectHostelBatchFunction(builder),
    editHostelBatch: editHostelBatchFunction(builder),
    deleteHostelBatch: deleteHostelBatchFunction(builder),

    getHostelAllStandard: getHostelAllStandardFunction(builder),
    createHostelStandard: createHostelStandardFunction(builder),
    deleteApplicationByHostel: deleteApplicationByHostelFunction(builder),
    exportFilterDataByHostel: exportFilterDataByHostelFuction(builder),
    getHostelLinkedList: getHostelLinkedListFunction(builder),
    addHostelLinkedInstitute: addHostelLinkedInstituteFunction(builder),
  }),
});

export const {
  useHostelDetailQuery,
  useHostelActivateMutation,
  useHostelEidtActivateMutation,
  useHostelCoverUploadMutation,
  useHostelUnitCoverUploadMutation,
  useHostelRoomCoverUploadMutation,
  useGetHostelFeeStructureListQuery,
  useGetHostelWardenListQuery,
  useGetHostelUnitListQuery,
  useGetHostelHostelitesListQuery,
  useAddHostelUnitMutation,
  useGetHostelUnitDetailQuery,
  useAddRoomHostelUnitMutation,
  useGetRoomListHostelUnitQuery,
  useGetRoomDetailHostelQuery,
  useGetHostelRulesQuery,
  useAddHostelRulesMutation,
  useEditHostelRulesMutation,
  useGetHostelFormQuery,
  useUpdateHostelFormMutation,
  useGetHostelApplyApplicationListQuery,
  useUserApplyHostelMutation,
  useCreateHostelApplicationMutation,
  useGetApplicationRequestedListQuery,
  useGetApplicationSelectedListQuery,
  useGetApplicationConfirmListQuery,
  useGetOngoingApplicationListQuery,
  useGetCompletedApplicationListQuery,
  useCancelApplicantRequestByHostelMutation,
  useAcceptApplicantRequestByHostelMutation,
  useGetHostelAppliciontDetailQuery,
  useCompleteHostelApplicationMutation,
  useConfirmStudentModeByHostelMutation,
  useRejectStudentModeByHostelMutation,
  useEditStructureByHostelMutation,
  useCollectStudentFeesByHostelMutation,
  useRefundStudentFeesByHostelMutation,
  useAllotBedByHostelMutation,
  useApplicantHostelRemainingFeeMutation,
  useRefundAmountByHostelMutation,
  useGetStudentRoommateListQuery,
  useCancelHostelApplicationByStudentMutation,
  useConfirmHostelApplicationByStudentMutation,
  useGetAnnouncementListByHostelQuery,
  useAddAnnouncementByHostelMutation,
  useGetReceiptListByHostelQuery,
  useOneReceiptActionByHostelMutation,
  useGetPendingFeeByHostelQuery,
  useOneReceiptReApplyByStudentMutation,
  usePaymentOfflineFeeHostelByStudentMutation,
  useSubmitCashToFinanceByHostelMutation,
  useAddHostilesExcelByHostelMutation,
  useGetRenewalApplicationListByHostelQuery,
  useGetRenewalSelectListByHostelQuery,
  useGetRenewalRenewedListByHostelQuery,
  useGetRenewalAllotListByHostelQuery,
  useGetRenewalCancelListByHostelQuery,
  useGetRenewalListByStudentQuery,
  useSelectRenewalByHostelMutation,
  useCancelRenewalByHostelMutation,
  useSelectRenewalByStudentMutation,
  useCancelRenewalByStudentMutation,
  useCollectRenewalFeeByHostelMutation,
  useRenewalAllotBedByHostelMutation,
  useCancelConfirmRenewalByHostelMutation,
  useHostelGetSiteInfoQuery,
  useHostelUpdateSiteInfoMutation,
  useAddModeratorByHostelMutation,
  useGetModeratorByHostelQuery,
  useUpdateModeratorByHostelMutation,
  useDeleteModeratorByHostelMutation,
  useGetMasterDepositByHostelQuery,
  useGetAllDepositRefundByHostelQuery,

  useHostelExportApplicantApplicatonMutation,
  useGetAllExcelByHostelManagerQuery,
  useUpdateExcelByHostelManagerMutation,
  useDeleteExcelByHostelManagerMutation,

  useGetHostelAllBatchQuery,
  useCreateHostelBatchMutation,
  useSelectHostelBatchMutation,
  useEditHostelBatchMutation,
  useDeleteHostelBatchMutation,
  useGetHostelAllStandardQuery,
  useCreateHostelStandardMutation,
  useDeleteApplicationByHostelMutation,
  useExportFilterDataByHostelMutation,
  useGetHostelLinkedListQuery,
  useAddHostelLinkedInstituteMutation,
} = hostelApiDynamic;
